# Generated by Django 4.0.4 on 2022-07-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0002_alter_diary_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='pub_date',
            field=models.DateTimeField(default='', verbose_name='date published'),
        ),
    ]
